spring.application.name=mynotebook
spring.datasource.url=jdbc:mysql://localhost:3306/mynotebook
spring.datasource.username=root
spring.datasource.password=Sneider07.

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
